export const Orchids = [
    {id: 1,
     name: 'Taichung beauty', 
     rating: 5, 
     isSpecial: 'true',
     color: 'pink', 
     origin: 'Taiwan', 
     category: 'Cattleya',
    img:'../../../public/assets/images/taichung.jpg',
    price: '$2,000',
    info: 'Taichung Beauty is a vibrant orchid from the Cattleya genus, featuring striking pink flowers. Originating from Taiwan, it is highly valued for its unique and radiant appearance, commonly used in floral displays and exhibitions for its beauty and elegance.',
    video: 'https://www.youtube.com/watch?v=jsTFfbok8v0'},

    {id: 2, 
    name: 'Shenzhen Nongke', 
    rating: 5, 
    isSpecial: 'false', 
    color: 'green', 
    origin: 'Chinese', 
    category: 'none', 
    img:'../../../public/assets/images/lan-nongke.jpg',
    price: '$202,000',
    info: 'Shenzhen Nongke is a remarkable orchid variety known for its stunning green flowers with intricate patterns. Developed in China, it represents a significant achievement in orchid cultivation. This unique orchid is prized for its rarity and exquisite beauty, making it a favorite among collectors and enthusiasts alike.',
    video: 'https://www.youtube.com/watch?v=i0pRSzuIvBU'},

    {id: 3, 
    name: 'Rothschild', 
    rating: 5, 
    isSpecial: 'true', 
    color: 'red', 
    origin: 'Malaysia', 
    category: 'Cypripediinae', 
    img:'../../../public/assets/images/ros.jpg',
    price: '$6,000',
    info: 'Rothschild is an exquisite orchid from the Cypripedioideae subfamily, characterized by its striking red flowers and distinctive striped patterns. Native to Malaysia, this rare orchid is highly sought after by collectors for its unique beauty and elegance. Its captivating appearance makes it a popular choice for floral displays and exhibitions.',
    video: 'https://www.youtube.com/watch?v=i0pRSzuIvBU'},

    {id: 4, 
    name: 'Odontoglossum', 
    rating: 5, 
    isSpecial: 'false', 
    color: 'pink', 
    origin: 'North Andes', 
    category: 'Oncidiinae', 
    img:'../../../public/assets/images/odo.jpg',
    price: '$100,000',
    info: 'Odontoglossum is a diverse genus of orchids known for their stunning and intricate flowers, often featuring vibrant colors and unique patterns. Native to the cool mountainous regions of Central and South America, these orchids thrive in cooler climates and are highly valued for their beauty. They are popular among orchid enthusiasts and collectors for their captivating appearance and variety.',
    video: 'https://www.youtube.com/watch?v=R14rHvax3ds'},
]    